apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fhir-client
  template:
    metadata:
      labels:
        app: fhir-client
    spec:
      containers:
        - name: fhir-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5001
          env:
            - name: FHIR_BASE_URL
              value: {{ .Values.fhirBaseUrl }}
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 30
      imagePullSecrets:
        - name: ghcr-pull-secret
