apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-pvc
  namespace: dicom-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  namespace: dicom-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
        - name: orthanc
          image: docker.io/jodogne/orthanc-plugins:latest
          ports:
            - containerPort: 8042
          volumeMounts:
            - mountPath: /var/lib/orhtanc/db
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: orthanc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace: dicom-lab
spec:
  selector:
    app: orthanc
  ports:
    - port: 8042
      targetPort: 8042