apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-pvc
  namespace: dicom-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  generateName: dicom-lab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
        - name: orthanc
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8042
          volumeMounts:
            - mountPath: /var/lib/orthanc/db
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: orthanc-pvc