name: Build and Push fhir-client

on:
  push:
    branches: [main]
    paths:
      - project-2/**

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checout@v4

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: project-2
          push: true
          tags: ghcr.io/faraz2079/fhir-client:latest
